# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgsrc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemimages',
            name='item',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='size',
        ),
        migrations.DeleteModel(
            name='ItemImages',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.ManyToManyField(to='clothes.ItemSize'),
        ),
    ]
