# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20171120_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothes.ItemGroup'),
        ),
    ]
