# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_auto_20171120_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('male', 'Male')], default='male', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('pink', 'Pink'), ('beige', 'Beige'), ('white;blue', 'White and Blue'), ('black', 'Black'), ('Blue', 'Blue'), ('brown', 'Brown'), ('grey', 'Grey'), ('navy', 'Navy'), ('red', 'Red'), ('white', 'White'), ('green', 'Green')], max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('desertboots', 'Desert Boots'), ('sunglasses', 'Sunglasses'), ('sweatshirt', 'Sweatshirt'), ('cap', 'Cap'), ('wovenbelt', 'Woven Belt'), ('boatshoes', 'Boat Shoes'), ('chelsea', 'Chelsea Boots'), ('shoes', 'Shoes'), ('chinos', 'Chinos'), ('leathershoes', 'Leather Shoes'), ('trainers', 'Trainers'), ('tshirt', 'T-Shirt'), ('poloshirt', 'Polo Shirt'), ('bomber', 'Bomber'), ('windbreaker', 'Windbreaker'), ('jeans', 'Jeans'), ('shirt', 'Shirt'), ('belt', 'Belt')], max_length=60),
        ),
    ]
