# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_auto_20171127_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.AddField(
            model_name='outfit',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('male', 'Male')], default='male', max_length=30),
            preserve_default=False,
        ),
    ]
